// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMHW9g8cmh4HBjJM_sa6lZPQ8MfdMBpoo',
    appId: '1:1023990619577:android:9509883e84f5551f626a68',
    messagingSenderId: '1023990619577',
    projectId: 'convo-4b456',
    storageBucket: 'convo-4b456.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ41NBw2kxNKyZxL4-XyYNFxCUvnN9TmA',
    appId: '1:1023990619577:ios:ad1e87db9a0c8840626a68',
    messagingSenderId: '1023990619577',
    projectId: 'convo-4b456',
    storageBucket: 'convo-4b456.appspot.com',
    iosClientId:
        '1023990619577-emq95m6reqv7loiq0glfbem31fo6d6mg.apps.googleusercontent.com',
    iosBundleId: 'brogrammer.developments.chatAlphaSept',
  );

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDDTE1QD169pesqVWdPB9kYoPDv9MDu0xM",
      authDomain: "convo-4b456.firebaseapp.com",
      projectId: "convo-4b456",
      storageBucket: "convo-4b456.appspot.com",
      messagingSenderId: "1023990619577",
      appId: "1:1023990619577:web:468892ff20203a08626a68",
      measurementId: "G-QHLZ43S9G3");
}
